package javainterpreter.clazz;

/**
 *
 * @author Attila
 */
public enum ConstantPoolElemType {
    UTF8, INT, FLOAT, LONG, DOUBLE, CLASSREF, STRINGREF, FIELDREF, METHODREF,
    INTERFACE_METHODREF, NAME_AND_TYPE_DESCRIPTOR, METHODHANDLE, 
    METHODTYPE_INFO, INVOKEDYNAMIC_INFO;
}
